name = "Relearn"
license = "MIT"
licenselink = "https://github.com/McShelby/hugo-theme-relearn/blob/main/LICENSE"
description = "A theme for Hugo designed for documentation"
homepage = "https://github.com/McShelby/hugo-theme-relearn"
demosite = "https://mcshelby.github.io/hugo-theme-relearn"
tags = ["dark", "docs", "light", "multilingual", "responsive"]
features = ["breadcrumbs", "boxes", "buttons",
  "customizable", "color variants",
  "dark", "docs", "documentation",
  "expand",
  "favicon", "file inclusion", "font awesome",
  "hidden pages",
  "i18n", "ie11", "image resizing", "include", "internet explorer",
  "light", "lightbox", "logo",
  "menu", "mermaid", "multilingual", "mobile",
  "nested sections", "notice",
  "openapi specification", "oas", "offline usable",
  "print", "printable",
  "responsive", "rss",
  "sidebar", "sitemap",
  "search", "subtheme", "swagger", "swaggerui", "syntax highlighting",
  "table of contents", "tabs", "tags", "themeable", "themes", "toc"]

[module]
  [module.hugoVersion]
    min = "0.93.0"

[author]
  name = "SÃ¶ren Weber"
  homepage = "https://github.com/McShelby"

[original]
  author = "Mathieu Cornic"
  homepage = "https://learn.netlify.app"
  repo = "https://github.com/matcornic/hugo-theme-learn"
